network:
  address: ":1947"
  max_connections: 1000
  max_message_size: 4096
  idle_timeout: 10m
persistence:
  mode: wal_and_dump
observability:
  address: ":2113"
  pprof: false
wal:
  sync_commit: off
  flushing_batch_length: 8192
  flushing_batch_timeout: 1000ms
  queue_capacity: 16384
  max_segment_size: 64MB
  data_directory: ./fq_data-slave/wal/
engine:
  type: in_memory
  partitions: 10
  clean_interval: 5m
  limit_event_queue_capacity: 16
dump:
  interval: 1m
  directory: ./fq_data-slave/
replication:
  replica_type: slave
  replica_id: "replica-1"
  master_address: ":1946"
  sync_interval: 1s
logging:
  level: info
