network:
  address: ":1945"
  max_connections: 1000
  max_message_size: 4KB
  idle_timeout: 10m
  auth:
    tokens:
      - { role: admin, token_env: FQ_ADMIN_TOKEN }
      - { role: rw, token_env: FQ_RW_TOKEN }
      - { role: ro, token_env: FQ_RO_TOKEN }
#  tls:
#    cert_file: ./certs/server.crt
#    key_file: ./certs/server.key
#    client_ca_file: ./certs/ca.crt
#    min_version: "1.3"
persistence:
  mode: wal_and_dump
observability:
  address: ":2112"
  pprof: false
wal:
  sync_commit: off
  flushing_batch_length: 8192
  flushing_batch_timeout: 10ms
  queue_capacity: 16384
  max_segment_size: 64MB
  data_directory: ./fq_data/wal/
engine:
  type: in_memory
  partitions: 16
  wal_apply_workers: 1
  key_index: false
  clean_interval: 5m
  limit_event_queue_capacity: 16
dump:
  interval: 1m
  directory: ./fq_data/
compression:
  wal: zstd          # none|s2|zstd
  dump: zstd         # none|s2|zstd
  replication: zstd  # none|s2|zstd
  min_frame_size: 512
replication:
  replica_type: master
  master_address: ":1946"
  sync_interval: 1s
  auth:
    token_env: FQ_REPLICATION_TOKEN
#  tls:
#    cert_file: ./certs/server.crt
#    key_file: ./certs/server.key
#    client_ca_file: ./certs/ca.crt
#    min_version: "1.3"
logging:
  level: info
