FROM alpine:3.22

ARG TARGETPLATFORM
WORKDIR /app
COPY ${TARGETPLATFORM}/fq ./fq
COPY ${TARGETPLATFORM}/fq-cli ./fq-cli
COPY config.yml ./config.yml

RUN mkdir -p /app/data/wal && chown nobody: /app -R

USER nobody
EXPOSE 1945 1946 2112
ENTRYPOINT ["/app/fq"]
