FROM alpine:3.22@sha256:14358309a308569c32bdc37e2e0e9694be33a9d99e68afb0f5ff33cc1f695dce

ARG TARGETPLATFORM
WORKDIR /var/lib/fq
RUN mkdir -p /var/lib/fq/data/wal /var/lib/fq/certs /etc/fq && chown nobody: /var/lib/fq -R

COPY ${TARGETPLATFORM}/fq ./fq
COPY ${TARGETPLATFORM}/fq-cli ./fq-cli
COPY config.yml /etc/fq/config.yml

USER nobody
EXPOSE 1945 1946 2112
ENTRYPOINT ["/var/lib/fq/fq"]
